---
title: "Informe de actividades de la Administracion 2020-2024 la UACM"
author: "Rectoria"
date: "2020-2024"
output:
#  revealjs::revealjs_presentation:
#    transition: slide
#    slideNumber: true
#    center: true
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    #theme: lumen
    #theme: cosmo
    #theme: darkly
    theme: flatly
    #theme: journal
    #theme: paper
    #theme: readable
    #theme: sandstone
    #theme: simplex
    #theme: spacelab
    #theme: yeti
    #theme: cerulean
    #theme: bootstrap
    #highlight: tango
    #layout: default
    css: styles.css
  word_document: default
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
```

# [Presentacion](Presentacion.html)
<button onclick="location.href='Presentacion.html'">Presentacion</button>

# [Informe](Informes.html)
<button onclick="location.href='Informes.html'">Informe</button>

# [Comunicados](Comunicados.html)
<button onclick="location.href='Comunicados.html'">Comunicados</button>

# [Vinculacion](Vinculacion.html)
<button onclick="location.href='Vinculacion.html'">Vinculacion</button>

# [Videos](Videos.html)
<button onclick="location.href='Videos.html'">Videos</button>

# [Entrevistas](Entrevistas.html)
<button onclick="location.href='Entrevistas.html'">Entrevistas</button>

# [Oferta Acdémica](OfertaAcademica.html)
<button onclick="location.href='OfertaAcademica.html'">Oferta Académica</button>

# [Presupuesto de Ingresos](Presupuesto.html)
<button onclick="location.href='Presupuesto.html'">Presupuesto de Ingresos</button>

# [Trabajo Legislativo - Iniciativas enviadas](TrabajoLegislativo.html)
<button onclick="location.href='TrabajoLegislativo.html'">Trabajo Legislativo - Iniciativas enviadas</button>

# [Documentos, informes  y diagnosticos elaborados](Documentos.html)
<button onclick="location.href='Documentos.html'">Documentos, informes y diagnósticos elaborados</button>

# [Asuntos destacados por coordinaciones](Coordinaciones.html)
<button onclick="location.href='Coordinaciones.html'">Asuntos destacados por coordinaciones</button>

# [Balance](Balance.html)
<button onclick="location.href='Balance.html'">Balance</button>





<style>
.button-container {
  display: grid;
  grid-template-columns: repeat(1, 1fr); /* Organiza en 3 columnas */
  grid-gap: 15px; /* Espacio entre botones */
}

.button-container button {
  width: 115px; /* Cambia el tamaño de los botones */
  height: 115px;
  padding: 15px;
  font-size: 12px;
  background-color:  #8B0000; /* Cambia el color de fondo de los botones a naranja */
  color: #C0C0C0; /* Cambia el color del texto de los botones a gris plateado */
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-container button:hover {
  background-color: #FF6347; /* Cambia el color de fondo al pasar el ratón sobre los botones */
}
</style>

<div class="button-container">
  <button onclick="location.href='index.html'">Inicio</button>
  <button onclick="location.href='Presentacion.html'">Presentacion</button>
  <button onclick="location.href='Informes.html'">Informe</button>
  <button onclick="location.href='Vinculacion.html'">Vinculacion</button>
  <button onclick="location.href='Comunicados.html'">Comunicados</button>
  <button onclick="location.href='Videos.html'">Videos</button>
  <button onclick="location.href='Entrevistas.html'">Entrevistas</button>
  <button onclick="location.href='OfertaAcademica.html'">Oferta Académica</button>
  <button onclick="location.href='Presupuesto.html'">Presupuesto de Ingresos</button>
  <button onclick="location.href='TrabajoLegislativo.html'">Trabajo Legislativo - Iniciativas enviadas</button>
  <button onclick="location.href='Documentos.html'">Documentos, informes y diagnósticos elaborados</button>
  <button onclick="location.href='Coordinaciones.html'">Asuntos destacados por coordinaciones</button>
  <button onclick="location.href='Balance.html'">Balance</button>
</div>
