---
title: "Vinculacion"
date: "2024-04-22"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    #theme: lumen
    #theme: cosmo
    #theme: darkly
    #theme: flatly
    #theme: journal
    #theme: paper
    #theme: readable
    #theme: sandstone
    #theme: simplex
    theme: spacelab
    #theme: yeti
    #theme: cerulean
    #theme: bootstrap
    #highlight: tango
    #layout: default
    #css: styles.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Informe general de gestion
En esta administración de la UACM se han retomado vigorosamente las relaciones y acciones de vinculación y cooperación con instituciones públicas y privadas, así como con organismos autónomos y especializados, nacionales e internacionales. La finalidad, dar a la universidad, a sus estudiantes y académicos, espacios de colaboración que potencien su proceso de formación y su trabajo de investigación. Los convenios que la Rectoría ha signado en esta gestión, son:


ANUIES - Constancia de ingreso de la UACM a la Asociación Nacional de Universidades e Instituciones de Educación Superior de la República Mexicana, A.C. (ANUIES, A.C.), por acuerdo de su Asamblea General y con fundamento en los artículos Noveno y Décimo Cuarto, fracción V de su Estatuto. <button onclick="'">Descargar</button>

Asociación Asociación Sindical de Sobrecargos de Aviación de México, "ASSA de México” - Llevar a cabo el proyecto de investigación sobre condiciones laborales y de salud que presentan las personas agremiadas de ASSA. Dicho proyecto de investigación es encabezado por las profesoras de la UACM: Mtra. Claudia Alicia López Ortiz, Dra. Ma. Elena Durán Lizárraga y la Dra. Roselia Arminda Rosales Flores.	<button onclick="'">Descargar</button>

Basílica de Guadalupe de la Ciudad de México - Intercambio de estudiantes para la realización de la asignatura de prácticas profesionales del plan de estudios de la licenciatura de protección civil y gestión de riesgos de la UACM. <button onclick="'">Descargar</button>

Benemérita Universidad Autónoma de Puebla (BUAP) - Unir esfuerzos con miras a formalizar acciones de cooperación y vinculación científica y técnica entre académicos de ambas instituciones. <button onclick="'">Descargar</button>

Centro de Investigaciones y Estudios Superiores en Antropología Social (CIESAS) - Colaboración académica en docencia, investigación, publicaciones, difusión cultural y extensión universitaria. Asimismo, favorecer el intercambio académico y estudiantil en proyectos conjuntos.	<button onclick="'">Descargar</button>

Centro Nacional de Prevención y Desastres, Gobierno de México - Convenio a través del cual la UACM forma parte de la “Red Nacional de Escuelas e Instituciones para la Capacitación, Certificación y Profesionalización en Protección Civil y Gestión Integral de Riesgo”	<button onclick="'">Descargar</button>

Colegio de México (Colmex) - Colaboración académica en docencia, investigación, publicaciones, difusión cultural y extensión universitaria. Asimismo, favorecer el intercambio académico y estudiantil en proyectos conjuntos.	<button onclick="'">Descargar</button>

Colegio de San Idelfonso, UNAM - Exposición de la obra que resguarda la universidad del artista plástico Vladimir Kibalchich Russakov, que alberga en el Centro Vlady.	<button onclick="'">Descargar</button>

Consejo Ciudadano para la Seguridad y Justicia - Brindar a la población de la UACM herramientas y servicios para enfrentar fenómenos de inseguridad y violencia.	<button onclick="'">Descargar</button>

Consejo Nacional contra las Adicciones (Conadic), Servicio de  Atención Psiquiátrica (SAP) y Secretariado Técnico de Consejo Nacional de salud Mental (STCONSAME), Gobierno de México - Desarrollar proyectos y acciones de educación, formación e investigación en materia de atención a la salud mental, adicciones y política pública de drogas, para que a través de diversas actividades los estudiantes de la universidad obtengan un conocimiento profundo y certero sobre estos temas y estén en posibilidad de atender con profesionalismo las acciones de política pública.	<button onclick="'">Descargar</button>

Facultad latinoamericana de Ciencias Sociales (FLACSO) - Colaboración para la elaboración de un diagnóstico sobre la factibilidad de la construcción, funcionamiento y consolidación de una plataforma abierta, accesible y unificada sobre la información del agua en cuencas de México. Proyecto liderado en la UACM por la profesora Dra. Karina Beatriz Kloster.	<button onclick="'">Descargar</button>

Fonoteca Nacional, Gobierno de México - Digitalización del patrimonio sonoro de la UACM – Centro Académico de la Memoria de Nuestra América (Camena) y acceso a la Fonoteca virtual. Adicionalmente el convenio contempla el acceso, desde las bibliotecas de la UACM, al fondo digital de la Fonoteca Nacional, habiendo parte la Universidad de la Red de Audiotecas de México.	<button onclick="'">Descargar</button>

Instituto de Atención y Prevención de las Adicciones de la Ciudad de México (IAPA), Gobierno de la Ciudad de México - Conjugar experiencias y esfuerzos en la planeación, diseño e instrumentación de programas, estrategias y acciones orientadas a la atención integral para la prevención del consumo de sustancias psicoactivas con la cooperación y participación ciudadana en beneficio de la población de la Ciudad México.	<button onclick="'">Descargar</button>

Instituto de Geofísica de UNAM - Intercambio de estudiantes para la realización de la asignatura de prácticas profesionales del plan de estudios de la licenciatura de protección civil y gestión de riesgos de la UACM.	<button onclick="'">Descargar</button>

Instituto de Transparencia, Acceso a la Información Pública, Protección de Datos Personales y Rendición de Cuentas de la Ciudad de México, INFO CDMX - Desarrollar programas y proyectos de trabajo en áreas de interés y beneficio mutuo, mimas que se sustenten en acciones de investigación, capacitación, asesorías, intercambio académico y difusión de la cultura de la transparencia. Adicionalmente el convenio contempla la realización conjunta de seminarios, diplomados y cursos de capacitación y formación profesional en materia de derecho a la información y transparencia.	<button onclick="'">Descargar</button>

Instituto Nacional de Antropología e Historia (INAH), Gobierno de México - Colaboración en los campos de la docencia, investigación y publicaciones. Actividades conjuntas de extensión, vinculación, cooperación y difusión cultural interuniversitarias. Servicio social y prácticas profesionales.	<button onclick="'">Descargar</button>

Instituto Nacional de Astrofísica, Óptica y Electrónica "El INAOE" - Colaboración conjunta para la capacitación, asesorías, cursos, talleres, seminarios, conferencias, así como para desarrollar conjuntamente posibles proyectos de investigación y desarrollo tecnológico y, en general, alentar aquellas acciones que conduzcan al fortalecimiento del quehacer científico y tecnológico en las áreas de interés mutuo.	<button onclick="'">Descargar</button>

Instituto Nacional de Psiquiatría Juan Ramon de la Fuente Muñiz - Cooperación, intercambio y concertación institucional en la promoción y desarrollo de proyectos de investigación de interés mutuo.	<button onclick="'">Descargar</button>

Instituto Politécnico Nacional (IPN) - Colaboración académica en docencia, investigación, publicaciones, difusión cultural y extensión universitaria. Asimismo, favorecer el intercambio académico y estudiantil en proyectos conjuntos.	<button onclick="'">Descargar</button>

Instituto Rosario Castellanos - Operar de manera conjunta el centro académico de cooperación Interinstitucional el Oasis en la Alcaldía magdalena Contreras en donde la universidad desarrolla un centro cultural y de extensión universitaria.	 <button onclick="'">Descargar</button>

MEMORIA, Coordinación de Memoria Histórica y Cultural de México, Gobierno de México. - Dos convenios específicos: uno para digitalizar parte del acervo en resguardo de CAMENA-UACM; y, otro, para la digitalización de las obras del artista plástico Vladimir Kibalchich Russakov, que alberga el Centro Vlady de la UACM.	<button onclick="'">Descargar</button>

PROCINE: Fideicomiso para la Promoción y Desarrollo del Cine Mexicano en la Ciudad de México, Gobierno de la Ciudad de México - Desarrollar proyectos y acciones concretas de investigación, formación, certificación, difusión, cooperación, producción editorial y exhibición sobre el cine y la industria cinematográfica en beneficio de la comunidad universitaria y de las personas próximas a sus planteles y sedes. Además de un programa de servicio social y prácticas profesionales.	<button onclick="'">Descargar</button>

Red de la Unión de Universidades de América Latina y el Caribe (UDUAL) - Red de instituciones de educación superior más grande, antigua y consolidada de la región. Avalada por la UNESCO como organismo de asesoría y consulta, agrupa a más de 200 instituciones de educación superior, tanto públicas, como privadas. Los objetivos de esta red son la promoción de la cooperación universitaria, la integración latinoamericana a través de la internacionalización de la educación superior, la mejora de la calidad educativa, la difusión del conocimiento y la defensa de la autonomía universitaria.	 <button onclick="'">Descargar</button>

Red de Transportes de Pasajeros de la Ciudad de México (RTP), Gobierno de la Ciudad de México - Apoyo con rutas de transporte con autobuses de RTP para el apoyo a la comunidad de la UACM. Recorridos diarios de estaciones de metro específicas a los planteles: San Lorenzo Tezonco, Casa Libertad y Cuautepec.	<button onclick="'">Descargar</button>

RENAPO: Dirección General del Registro Nacional de Población e Identidad, Gobierno de México - Promover la adopción, el uso, la certificación y la validación de la Clave Única de Registro de Población (CURP) entre la comunidad universitaria.	<button onclick="'">Descargar</button>

Secretaria de Cultura de la Ciudad de México - Colaboración para llevar a cabo la planeación, diseño, instrumentación de eventos, proyectos, programas, asesorías, investigación, talleres, seminarios, mesas de trabajo, educación, formación y de actividades en materia cultural.	<button onclick="'">Descargar</button>

Secretaría de Educación, Ciencia, Tecnología e Innovación (SECTEI), Gobierno de la Ciudad de México-Red Ecos - La Red es un mecanismo para la colaboración, interacción y vinculación inter-institucional, trans-disciplinar y multisectorial entre las principales Universidades, Instituciones de Educación Superior, Centros Públicos de Investigación, Gobierno, Sociedad Civil y el sector productivo que cohabitan en nuestra Ciudad. El objetivo principal es generar espacios de diálogo, intercambio y trabajo que den lugar a proyectos conjuntos que incidan en la transformación de nuestra realidad y coadyuven a resolver algunas de las principales problemáticas de la Ciudad de México.	<button onclick="'">Descargar</button>

Secretaría de Inclusión y Bienestar Social, Gobierno de la Ciudad de México - Desarrollar proyectos y acciones de investigación a favor de los grupos sociales de atención prioritaria en la Ciudad de México, para que a través de diversas actividades los alumnos de “LA UACM” aporten su experiencia académica para garantizar la promoción, respeto y visibilización de los derechos humanos, sociales y culturales de esos grupos sociales.	 <button onclick="'">Descargar</button>

Secretaría de las Mujeres, Gobierno de la Ciudad de México - Impulso a programas de servicio social y prácticas profesionales, se desarrollen campañas de formación y capacitación temas de violencia de género, recomendaciones y diagnóstico sobre transversalidad de la perspectiva de género en la administración de la Universidad, campañas de concientización y promoción de espacios seguros y libres de violencia hacia las mujeres.	<button onclick="'">Descargar</button>

Secretaría de Relaciones Exteriores (SER), Acervo Histórico Diplomático, Gobierno de México - Acciones conjuntas para la preservación y protección del patrimonio histórico y cultural de los acervos documentales, fotográficos y bibliohemerográficos de la UACM; en específico los resguardados en CAMENA. Adicionalmente el convenio contempla la promoción de la investigación y difusión de los archivos que se resguardan en ambas instituciones.	<button onclick="'">Descargar</button>

Sistema para el Desarrollo Integral de la Familia de la Ciudad de México (DIF-CDMX), Gobierno de la Ciudad de México - Programas de Servicio Social y Prácticas Profesionales que beneficien a las y los estudiantes de la UACM, así como cursos-talleres, asesorías, diplomados y actividades extracurriculares de difusión cultural y extensión universitaria en beneficio de toda la comunidad universitaria y de la Ciudad de México.	<button onclick="'">Descargar</button>

Sistema público de radiodifusión de la Ciudad de México: Capital 21 - Actividades conjuntas suponen transmisión y coproducción recíproca de contenidos para televisión y radio, prácticas profesionales y servicio social, formación y capacitación mutua y participación de académicos en programas de opinión de Capital 21.	<button onclick="'">Descargar</button>

Telecomunicaciones de México (TELECOMM), Financiera para el Bienestar, Gobierno de México - Desarrollar acciones específicas para la ejecución de proyectos y programas culturales, de extensión universitaria, de formación, capacitación, investigación, gestión y vinculación comunitaria en beneficio de todas las personas de la UACM.	<button onclick="'">Descargar</button>

Unidad de Vinculación de Química SA de CV, Facultad de Química de la UNAM y Facultad de Ciencias de la UNAM - Esquema de pruebas COVID a bajo costo para trabajadores y trabajadoras de la UACM. Pruebas realizadas por la Facultad de Ciencias de la UNAM.	 <button onclick="'">Descargar</button>

Universidad Autónoma de México (UAM) - Convenio específico: colaboración en el desarrollo del proyecto “Tejiendo Historias: programa radiofónico de comunicación pública del conocimiento y la cultura.”  En dicho proyecto la UACM, a través del profesor Mtro. Omar Zamora Sánchez, producirá cápsulas radiofónicas que serán transmitidas a través de radio UAM 94.1 FM	<button onclick="'">Descargar</button>

Universidad Autónoma del Estado de México (UAEM) - Desarrollo de actividades conjuntas encaminadas a la superación académica, la formación y la capacitación profesional, el desarrollo de la ciencia y la tecnología, la divulgación del conocimiento y la extensión universitaria en todos los campos del conocimiento en los que ambas universidades se desarrollan.	<button onclick="'">Descargar</button>

Universidad Autónoma Metropolitana (UAM) - Convenio Marco: Establecer las bases y acciones de colaboración a fin de desarrollar proyectos y programas de trabajo en aquellas áreas de interés y beneficio mutuo, relativas a la investigación, capacitación, asesorías, intercambio académico y difusión de la cultura.	<button onclick="'">Descargar</button>

Universidad de las Artes de Ecuador - Promover la cooperación interinstitucional y los vínculos entre ambas instituciones de educación superior con la finalidad de generar proyectos y acciones académicas, de investigación, producción , difusión, cooperación e innovación en beneficio de ambas comunidades universitarias.	<button onclick="'">Descargar</button>




<style>
.button-container {
  display: grid;
  grid-template-columns: repeat(1, 1fr); /* Organiza en 3 columnas */
  grid-gap: 5px; /* Espacio entre botones */
}

.button-container button {
  font-size: 12px;
  background-color:  #FFFF99; /* Cambia el color de fondo de los botones a naranja */
  color: #C0C0C0; /* Cambia el color del texto de los botones a gris plateado */
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.button-container button:hover {
  background-color: #FF6347; /* Cambia el color de fondo al pasar el ratón sobre los botones */
}
</style>

<div class="button-container">
  <button onclick="location.href='index.html'">Inicio</button>
  <button onclick="location.href='Presentacion.html'">Presentacion</button>
  <button onclick="location.href='Vinculacion.html'">Vinculacion</button>
  <button onclick="location.href='Comunicados.html'">Comunicados</button>
  <button onclick="location.href='Videos.html'">Videos</button>
  <button onclick="location.href='Entrevistas.html'">Entrevistas</button>
  <button onclick="location.href='OfertaAcademica.html'">Oferta Académica</button>
  <button onclick="location.href='Presupuesto.html'">Presupuesto</button>
  <button onclick="location.href='TrabajoLegislativo.html'">Trabajo Legislativo</button>
  <button onclick="location.href='Documentos.html'">Documentos</button>
  <button onclick="location.href='Coordinaciones.html'">Coordinaciones</button>
  <button onclick="location.href='Balance.html'">Balance</button>
</div>
